import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
		<html lang="en">
			<body className={inter.className}>
				<Header navigations={["about", "menu", "contact", "shop"]}>BlissBrew</Header>
				{children}
			</body>
		</html>
  );
}

export default RootLayout;
